default_platform(:mac)

platform :mac do
  desc "Capture macOS screenshot"
  lane :mac_screenshots do
    sh("cd .. && xcodegen generate")
    scan(project: "../TalliMac.xcodeproj", scheme: "TalliMacUITests")
    sh("mkdir -p ../fastlane/screenshots/mac && cp ~/Library/Containers/com.heyitsmejosh.tally.mac.uitests.xctrunner/Data/tmp/talli-mac-screenshots/*.png ../fastlane/screenshots/mac/")
  end

  desc "Build and upload a macOS TestFlight beta"
  lane :mac_beta do
    app_store_connect_api_key(
      key_id: "MUJM3PFMT4",
      issuer_id: "56091958-7499-4e11-b1e6-a101531bcb26",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_MUJM3PFMT4.p8")
    )
    sh("cd .. && xcodegen generate")
    gym(
      project: File.expand_path("../../TalliMac.xcodeproj", __FILE__),
      scheme: "TalliMac",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      clean: true
    )
    pilot(skip_waiting_for_build_processing: true)
  end
end
