devices([
  "iPhone 17 Pro",
  "iPhone 17 Pro Max"
])

languages([
  "en-US"
])

scheme("TalliUITests")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)
