devices([
  "iPhone 11 Pro Max",
  "iPhone 14 Plus"
])

languages([
  "en-US"
])

scheme("TalliUITests")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)
